name: Streamlit QA Automation
on: [push]

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install streamlit pandas numpy faiss-cpu pytest
      - name: Run App Tests
        run: |
          pytest tests/test_app.py

  build-docker:
    needs: test-app  # Syarat poin nomor 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t music-similarity-app:latest .
